# 1. Dirección de tu base de datos (usamos la que creaste: monstruomon_db)
spring.datasource.url=jdbc:mysql://localhost:3306/monstruomon_db?allowPublicKeyRetrieval=true&useSSL=false

# 2. Tu usuario de MySQL (por defecto suele ser root)
spring.datasource.username=root

# 3. CAMBIA ESTO por tu contraseña real de MySQL
spring.datasource.password=Curs026

# 4. El motor que usa Spring para hablar el idioma exacto de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 5. Esto hace que Spring NO te borre ni te modifique las tablas que ya tienes creadas con tus datos
spring.jpa.hibernate.ddl-auto=validate

# 6. Para que veas en la consola de Spring los comandos reales que hace por detrás (es súper útil)
spring.jpa.show-sql=true

# 7. Apaga el aviso de open-in-view para dejar la consola limpia y perfecta
spring.jpa.open-in-view=false